### ISSUE TITLE
About Could not apply withXml() to generated POM

### ISSUE THREAD

**Issue by Jadyli** [spxbhuhb/adaptive#30]
The same issue to me，https://github.com/vanniktech/gradle-maven-publish-plugin/issues/799

After debugging, I found that the error occurred in `org/jetbrains/kotlin/gradle/plugin/mpp/Publishing#rewritePom`. Whether the generated POM is rewritten is controlled by `kotlin.mpp.keepMppDependenciesIntactInPoms`. So, for now, I disabled it in `gradle.properties`, and then publishing the module to Maven worked fine.

```
kotlin.mpp.keepMppDependenciesIntactInPoms=true
```

**Comment by toth-istvan-zoltan** [comment]
Thank you for the solution.

I remember that I've encountered this issue, but to be honest, I don't remember where. How did you connect this repository with it?

Edit:

Oh, I see, Slack. :D

Thanks again, I'll look into it

https://kotlinlang.slack.com/archives/C3PQML5NU/p1716955162094439 (so I don't forget again)

**Comment by Jadyli** [comment]
Yes, but it's unclear what bugs this might cause

**Comment by toth-istvan-zoltan** [comment]
The project does not compile or it cannot be imported by other projects. I had to move parts around to make a workaround.

**Comment by Jadyli** [comment]
I have reported a bug to Gradle: https://github.com/gradle/gradle/issues/29793
